# Generated by Django 5.2.9 on 2025-12-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, verbose_name='생년월일'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', '남성'), ('F', '여성')], max_length=1, verbose_name='성별'),
        ),
        migrations.AlterField(
            model_name='user',
            name='job',
            field=models.CharField(blank=True, max_length=50, verbose_name='직업'),
        ),
        migrations.AlterField(
            model_name='user',
            name='real_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.CharField(blank=True, choices=[('서울특별시', '서울특별시'), ('부산광역시', '부산광역시'), ('대구광역시', '대구광역시'), ('인천광역시', '인천광역시'), ('광주광역시', '광주광역시'), ('대전광역시', '대전광역시'), ('울산광역시', '울산광역시'), ('세종특별자치시', '세종특별자치시'), ('경기도', '경기도'), ('강원특별자치도', '강원특별자치도'), ('충청북도', '충청북도'), ('충청남도', '충청남도'), ('전북특별자치도', '전북특별자치도'), ('전라남도', '전라남도'), ('경상북도', '경상북도'), ('경상남도', '경상남도'), ('제주특별자치도', '제주특별자치도')], max_length=20, verbose_name='지역'),
        ),
    ]
