# Generated by Django 5.2.9 on 2025-12-23 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_post_image'),
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='policies.policy', verbose_name='정책'),
        ),
    ]
