# Generated by Django 5.2.9 on 2025-12-19 06:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('plcyNo', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='정책번호')),
                ('plcyNm', models.CharField(max_length=200, verbose_name='정책명')),
                ('plcyExplnCn', models.TextField(verbose_name='정책설명')),
                ('lclsfNm', models.CharField(max_length=50, verbose_name='대분류')),
                ('mclsfNm', models.CharField(max_length=50, verbose_name='중분류')),
                ('plcyKywdNm', models.CharField(blank=True, max_length=100, null=True, verbose_name='키워드')),
                ('plcySprtCn', models.TextField(verbose_name='지원내용')),
                ('sprvsnInstCdNm', models.CharField(max_length=100, verbose_name='지역')),
                ('sprtTrgtMinAge', models.IntegerField(default=0, verbose_name='최소나이')),
                ('sprtTrgtMaxAge', models.IntegerField(default=0, verbose_name='최대나이')),
                ('bizPrdBgngYmd', models.CharField(blank=True, max_length=8, verbose_name='사업시작일')),
                ('bizPrdEndYmd', models.CharField(blank=True, max_length=8, verbose_name='사업종료일')),
                ('jobCd', models.CharField(blank=True, max_length=200, verbose_name='직업코드')),
                ('schoolCd', models.CharField(blank=True, max_length=50, verbose_name='학력코드')),
                ('aplyUrlAddr', models.URLField(blank=True, max_length=500, verbose_name='신청URL')),
                ('refUrlAddr1', models.URLField(blank=True, max_length=500, verbose_name='참고URL')),
                ('liked_users', models.ManyToManyField(blank=True, related_name='liked_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-plcyNo'],
            },
        ),
    ]
